name: GUIShop
main: com.pablo67340.GUIShop.Main.Main
<<<<<<< HEAD
version: 4.6
=======
version: 4.5
>>>>>>> ba20ce48b34a8d70afbca11e75b62f04b1f64cf9
author: pablo67340
description: Plugin for any server.